<?xml version="1.0" encoding="utf-8"?><Database Name="projectKTPM" Class="MyDbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=projectKTPM.mssql.somee.com;Initial Catalog=projectKTPM;User ID=khoa2181195_SQLLogin_1" SettingsObjectName="PlaneShare.Properties.Settings" SettingsPropertyName="projectKTPMConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Plane" Member="Planes">
    <Type Name="Plane">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Brand" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Size" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>